development:
  adapter: mysql
  host: localhost
  database: sanction_playground_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  host: localhost
  database: sanction_playground_test
  username: root
  password: 
  socket: /tmp/mysql.sock
